apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  ports:
  - name: 80-5000
    port: 5000
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote
  type: NodePort
status:
  loadBalancer: {}
