apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-svc
  name: db-svc
  namespace: database
spec:
  ports:
  - name: db
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db
  type: ClusterIP
status:
  loadBalancer: {}
